server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:  
  cloud:
    gateway:
      routes:
        - id: funky-service
          uri: http://funky-service:8082
          predicates:
            - Path=/funky/**
        - id: package-service
          uri: http://package-service:8081
          predicates:
            - Path=/package/**
        - id: eureka-server
          uri: http://service-registry:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://service-registry:8761
          predicates:
            - Path=/eureka/**

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          springframework:
            cloud:
              gateway: TRACE
              gateway.route.RouteDefinitionLocator: INFO

